// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type DoneTodo struct {
	TodoID string `json:"todoId"`
}

type History struct {
	TodoID    string    `json:"TodoID"`
	Text      string    `json:"text"`
	Done      bool      `json:"done"`
	CreatedAt time.Time `json:"created_at"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID        string     `json:"id"`
	Text      string     `json:"text"`
	Done      bool       `json:"done"`
	UserID    string     `json:"userID"`
	User      *User      `json:"user"`
	Histories []*History `json:"histories"`
}

type ToggleTodo struct {
	TodoID string `json:"todoId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
